CREATE TABLE `campRegistrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`camper1Name` varchar(255) NOT NULL,
	`camper1Dob` varchar(20) NOT NULL,
	`camper1Age` varchar(10) NOT NULL,
	`camper1Sex` varchar(10) NOT NULL,
	`camper2Name` varchar(255),
	`camper2Dob` varchar(20),
	`camper2Age` varchar(10),
	`camper2Sex` varchar(10),
	`camper3Name` varchar(255),
	`camper3Dob` varchar(20),
	`camper3Age` varchar(10),
	`camper3Sex` varchar(10),
	`parentFirstName` varchar(255) NOT NULL,
	`parentLastName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`address` varchar(500) NOT NULL,
	`city` varchar(255) NOT NULL,
	`state` varchar(50) NOT NULL,
	`zip` varchar(20) NOT NULL,
	`howDidYouHear` varchar(255),
	`programType` enum('3day','5day','daily') NOT NULL,
	`numCampers` int NOT NULL DEFAULT 1,
	`addFieldTrip` int NOT NULL DEFAULT 0,
	`addEarlyPickup` int NOT NULL DEFAULT 0,
	`addLatePickup` int NOT NULL DEFAULT 0,
	`anticipatedWeeks` text,
	`firstWeek` varchar(100) NOT NULL,
	`stripePaymentIntentId` varchar(255),
	`stripePaymentStatus` varchar(50) DEFAULT 'pending',
	`amountPaid` int NOT NULL DEFAULT 0,
	`agreedToTerms` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `campRegistrations_id` PRIMARY KEY(`id`)
);
