// GENERATED by scripts/build-playbook-corpus.mjs — do not edit by hand.
// Re-run that script after changing the SOP or playbook, then commit this file.
export type PlaybookChunk = { source: string; title: string; text: string };
export const PLAYBOOK_CORPUS: PlaybookChunk[] = [
  {
    "source": "Front Desk SOP",
    "title": "TMA Front Desk SOPs (current system)",
    "text": "# TMA Front Desk SOPs (current system)\n\nWritten against the CURRENT dashboard so staff can use it today. When the dashboard reorg lands, the view names in here get updated. Staff: Arfa (owner), Master Jo, Ms Anna, Ms Aniessa. Shared admin login.\n\n**The one rule that matters most right now:** several flows are unlinked or invisible in the admin (afterschool, camp waivers, supply/field-trip payments, paid-trial to lead). Until those are fixed, the manual cross-checks below are not extra work, they are the system. Telegram is the real-time signal; the weekly manual reconciliation is the safety net.\n\n---"
  },
  {
    "source": "Front Desk SOP",
    "title": "1. Daily open / close",
    "text": "## 1. Daily open / close\n\n**Morning (whoever opens):**\n1. Open the dashboard, land on **Today**. Confirm the day looks right.\n2. **Today's Calls**: confirm the AM Telegram \"trials today\" and \"daily call list\" landed. If missing by 9am, tell Arfa.\n3. **Trial Check-in**: have waiver + intake ready for anyone trialing today.\n4. Scan Telegram for overnight pickup/callback/after-hours calls. Action anything time-sensitive first.\n\n**Evening (whoever closes):**\n1. **Today's Calls**: every call has a status (contacted / no answer / voicemail). Nothing blank overnight.\n2. Cross-check the PM \"did they show?\" Telegram against **Trial Check-in**. No-shows without a note get flagged for tomorrow.\n3. **My Tasks**: close out or roll forward with a note.\n4. Skim Telegram for late payments; confirm each has its record (see SOP 5 for the ones with no table).\n\n---"
  },
  {
    "source": "Front Desk SOP",
    "title": "2. Lead to trial to enrolled",
    "text": "## 2. Lead to trial to enrolled\n\nTrigger: new lead (web form, FB ad, walk-in, phone).\n1. New leads land in **Leads** at `new_lead` automatically. FB leads sync every 15 min.\n2. The follow-up sequence starts automatically (dispatcher runs every 5 min). Your job is a live call, fast.\n3. After you talk to them, move **Leads** status to `contacted`, log in **Call History**.\n4. Trial booked (by you, voice agent, or sequence) moves to `trial_scheduled`. If the voice agent booked it, verify it shows in **Leads** / **Today's Calls**.\n5. 24h reminder sends automatically.\n6. `$99 trial paid` Telegram fires and status moves to `trial_paid`. **Watch-out:** the paid trial is not auto-linked to the lead. Confirm the matching lead updated; fix by hand if not.\n7. On trial day, check them in via **Trial Check-in** (`trial_attended`).\n8. No-show recovery kicks off automatically; follow up personally if no response in 48h.\n9. Enrolled families move to `enrolled` and should appear in **Enrolled Families**. Declines move to `lost` with a one-line reason. Never leave it blank.\n\n---"
  },
  {
    "source": "Front Desk SOP",
    "title": "3. Afterschool enrollment",
    "text": "## 3. Afterschool enrollment\n\nTrigger: parent signs up for afterschool.\n1. `afterschool enrollment signed` and (separately) `afterschool care paid` Telegram alerts fire. Parent gets the intake PDF + confirmation automatically.\n2. **Watch-out (manual step):** signature, payment, and the **Afterschool Roster** are three separate unlinked records. The roster does not auto-populate.\n3. Only after you see BOTH the signed alert AND the paid alert for a family, manually add the child to **Afterschool Roster**. Never add off one alert alone.\n4. Reconcile weekly (daily is safer): check every afterschool alert name against the roster. Paid + signed but missing from roster gets added immediately.\n5. Payment alert with no matching signature (or vice versa): do not roster them. Chase the missing piece first.\n\n---"
  },
  {
    "source": "Front Desk SOP",
    "title": "4. Camp registration",
    "text": "## 4. Camp registration\n\nTrigger: parent registers for camp.\n1. Registration + payment go through **Camp Registrations**. `camp paid` Telegram fires; parent gets the confirmation email.\n2. The camp waiver link email is sent automatically after registration.\n3. **Watch-out (invisible waiver):** when a parent signs the camp waiver, the ONLY confirmation is a `camp waiver` Telegram alert. There is no dashboard table for it. Do not look in **Waivers**; camp waivers are not there.\n4. To confirm a camp waiver before a child attends: search staff Telegram history for the family name + \"camp waiver\" near their registration date. If you cannot find it, assume unsigned. Text/call to resend before drop-off.\n5. Keep a running weekly list: `camp paid` and `camp waiver signed` are two separate checkboxes; both must be checked before a child is cleared.\n\n---"
  },
  {
    "source": "Front Desk SOP",
    "title": "5. One-off payments (supply fee, field trip)",
    "text": "## 5. One-off payments (supply fee, field trip)\n\nTrigger: supply-fee or field-trip payment.\n1. **Watch-out:** neither has an admin table. The only record is Stripe + the Telegram alert (`supply-fee paid` / `field-trip paid`). Field trip also emails the parent.\n2. Treat the Telegram alert as the in-the-moment signal, not the permanent record.\n3. **Manual reconciliation (weekly):** pull supply-fee + field-trip transactions from Stripe, cross-check against the Telegram alerts.\n4. Keep a manual log (name, item, date, amount) for every one-off payment. This is the only durable record outside Stripe. Do not skip it.\n5. Alert with no matching Stripe charge (or vice versa): flag immediately.\n\n---"
  },
  {
    "source": "Front Desk SOP",
    "title": "6. Phone vs voice agent",
    "text": "## 6. Phone vs voice agent\n\n1. The Retell inbound agent answers when staff cannot; it can book trials, take pickup requests, take callbacks.\n2. **Outbound voice (speed-to-lead, no-show, post-trial) is gated OFF until tested.** Manual follow-up calls are still your job until Arfa says it is live.\n3. If you are at the desk and it rings, answer live. A human answer beats the agent.\n4. Every call generates a Telegram alert. Watch for: voice-agent booked trial, pickup request, callback request. Verify each landed in **Today's Calls** / **Leads**.\n5. Log calls you handle in **Call History**.\n\n---"
  },
  {
    "source": "Front Desk SOP",
    "title": "7. Which link do I send?",
    "text": "## 7. Which link do I send?\n\nCheck **Links** in the dashboard for the current URL before sending from memory.\n\n| Situation | Send |\n|---|---|\n| Wants to book a trial | Trial booking link (or book it yourself in Leads) |\n| Registering for camp | Camp registration link |\n| Camp waiver | Camp waiver link (auto-sent after registration; resend if lost) |\n| Enrolling in afterschool | Afterschool enrollment link |\n| Paying supply fee | Supply-fee payment link |\n| Field trip | Field-trip payment link |\n| General / in-person waiver | In-person waiver link, or handle in person via Waivers |\n| Invoice / tuition question | Invoice Generator, or send the invoice |\n\n---"
  },
  {
    "source": "Front Desk SOP",
    "title": "8. Only Arfa handles",
    "text": "## 8. Only Arfa handles\n\n1. Stripe-vs-dashboard mismatches you cannot resolve with the manual steps above.\n2. Turning the outbound voice agent on/off or changing what the agent says.\n3. Recurring tuition billing (not automated yet; any tuition question beyond a one-time invoice).\n4. n8n workflow failures (missing cron Telegram, stuck lead, duplicates not caught).\n5. Refunds, disputes, any Stripe-level correction.\n6. Structural changes to Leads stages, Afterschool Roster, or Camp flow.\n7. New staff access, Telegram group membership, login issues.\n8. Anything a parent frames as legal / safety / liability (injury, waiver dispute, custody/pickup conflict)."
  },
  {
    "source": "Front Desk Playbook",
    "title": "Where things live",
    "text": "TMA Front Desk Playbook — Where Everything Lives Top Martial Arts Suwanee &middot; Front Desk Playbook Where everything lives in the new system One place to look up any person who touches TMA. Every lead, family, order, and form has one home now, so nobody gets cold-called after they have already signed up, and every alert points you to the right screen. Where do I look? Start here. Pick the row that matches the person in front of you. Prospects Someone interested, not signed up yet Use when a new person wants info or a trial , or you need to call people back and book them in. Holds: web inquiries, tour requests, Facebook leads, $99 & $49 trials. This is the call list and the calendar. Enrolled Families Already a paying student Use for current members : belts, attendance, after-school enrolled families, contact info. Holds: the student roster and after-school enrollments. These never sho"
  },
  {
    "source": "Front Desk Playbook",
    "title": "Where things live",
    "text": "w up in the call list. Orders Bought gear or a package Use when someone paid for pro-shop items, a bundle, or a sale and you need to fulfill it. Holds: pro-shop and seasonal sale orders. A purchase, not a person to chase. Camp Summer / seasonal camp Use for camp registrations and camp field-trip payments . Holds: camp registrations (already kept separate today, the model for the rest). Forms & Calls Paperwork and phone history Use to find a signed waiver, a transportation form, or a call recording . Holds: waivers, transportation forms, the voice-agent call log, and the test-call tool. The trial journey How a prospect moves from first contact to enrolled. Check-in decides \"showed up\" vs \"no-show.\" Step 1 New lead Came in from a form, ad, or call. -> Step 2 Contacted We reached out. Text or call logged. -> Step 3 Trial booked Day and time set. Shows on the calendar. -> Step 4 &middot; Che"
  },
  {
    "source": "Front Desk Playbook",
    "title": "Where things live",
    "text": "ck-in Showed up? Marked at the door: attended or no-show. -> Step 5 Enrolled Signed up. Moves to Enrolled Families. If no-show No-show -> recovery Automatic follow-up brings them back to book again, then closes out if there is no reply. What is changing Same information, organized so it is obvious who is who. Before &middot; everything in one pile Every type of person landed in the same lead list. Pro-shop buyers and enrolled families showed up in the \"call these new leads\" list. Staff could not tell a hot prospect from a paying customer at a glance. Emails went out as \"TMA Summer Camp\" even to martial-arts families. The same person could appear in two or three places with no clear home. Follow-ups fired from two different systems, sometimes twice. After &middot; one home each Five clear sections, driven by a record type on every entry. The call list shows only real prospects . Customers"
  },
  {
    "source": "Front Desk Playbook",
    "title": "Where things live",
    "text": "never resurface there. Prospects, Enrolled, Orders, Camp, and Forms each have their own screen. All email comes from one identity: Top Martial Arts <hello@tmatkd.com> . Every alert names the real source and links to the right section. Each automation has a single owner, so nothing double-fires. Every entry, sorted Where each thing comes from, what it really is, and where it now lives. Comes from What it is Lives in Free class form &middot; tour request &middot; Facebook lead Prospect Prospects (call list + calendar) $99 trial &middot; $49 back-to-school Trial Prospects (in a trial) After-School registration + waiver Enrolled Enrolled Families Pro-shop &middot; Christmas / seasonal sale Order Orders Camp registration &middot; camp field trip Camp Camp Waiver &middot; transportation form Form Forms & Calls Behind the scenes What the system now does for you automatically, without stepping"
  },
  {
    "source": "Front Desk Playbook",
    "title": "Where things live",
    "text": "on itself. One sender, correct labels All email goes out as Top Martial Arts. Staff alerts and Telegram pings name the real program, not a generic title. Prospects only on the call board Orders and enrolled families are filtered out, so \"call fast\" never points at someone who already paid. One owner per automation Reminders, no-show recovery, and call alerts each run from a single place, so nobody gets contacted twice. No duplicate people Submitting a form twice updates the same record instead of creating a second one to clean up later. TMA Top Martial Arts Suwanee Front desk reference &middot; new CRM structure"
  }
];
